version: "3"
services:
  ros_hello_world: 
    privileged: true
    # Colocar nombre de la imagen
    image: chuy7/ros_hello_world:practice2
    ports: 
      - 10000:10000
      - 5005:5005
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=burger
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix/
    network_mode: "host"
    

