# "my_robot" sera nuestro espacio de nombres (todos los controladores estaran dentro
# de este espacio de nombres).
my_robot:
  #Controlador para publicar los estados de las articulaciones
  joint_state_controller: 
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  # Para los controladores de posicion podemos definir "pid gains" (ganancias
  # del controlador PID).
  # El objetivo de los ajustes de los parametros PID es lograr que el bucle de control
  # corrija eficazmente y en el minimo tiempo los efectos de las perturbaciones.

  # Controladores de posicion
  joint1_position_controller: 
    type: "effort_controllers/JointPositionController"
    joint: joint1 # Nombre de una articulacion
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller: 
    type: "effort_controllers/JointPositionController"
    joint: joint2 # Nombre de una articulacion
    pid: {p: 100.0, i: 0.01, d: 10.0}